name: 'Terraform apply'

on:
  push:
    branches:
      - main

jobs:
  apply-global:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./global
    env: 
      TF_WORKSPACE: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.3
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Apply
        run: terraform apply -auto-approve

  apply-development:
    needs: apply-global
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./environments
    env: 
      TF_WORKSPACE: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.3
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Apply
        run: terraform apply -auto-approve

  apply-staging:
    needs: apply-development
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./environments
    env: 
      TF_WORKSPACE: stg
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.3
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Apply
        run: terraform apply -auto-approve